package org.cc.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cc.mybatis.model.Filter;
import org.cc.mybatis.model.FilterExample;

public interface FilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int countByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insert(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insertSelective(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    List<Filter> selectByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    Filter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExampleSelective(@Param("record") Filter record, @Param("example") FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExample(@Param("record") Filter record, @Param("example") FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKeySelective(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKey(Filter record);
}