package org.cc.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cc.mybatis.model.SourcePage;
import org.cc.mybatis.model.SourcePageExample;

public interface SourcePageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int countByExample(SourcePageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByExample(SourcePageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insert(SourcePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insertSelective(SourcePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    List<SourcePage> selectByExample(SourcePageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    SourcePage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExampleSelective(@Param("record") SourcePage record, @Param("example") SourcePageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExample(@Param("record") SourcePage record, @Param("example") SourcePageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKeySelective(SourcePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKey(SourcePage record);
}