package org.cc.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cc.mybatis.model.SourcePageCategory;
import org.cc.mybatis.model.SourcePageCategoryExample;

public interface SourcePageCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int countByExample(SourcePageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByExample(SourcePageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insert(SourcePageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insertSelective(SourcePageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    List<SourcePageCategory> selectByExample(SourcePageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    SourcePageCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExampleSelective(@Param("record") SourcePageCategory record, @Param("example") SourcePageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExample(@Param("record") SourcePageCategory record, @Param("example") SourcePageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKeySelective(SourcePageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKey(SourcePageCategory record);
}