package org.cc.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cc.mybatis.model.SourcePageFilter;
import org.cc.mybatis.model.SourcePageFilterExample;

public interface SourcePageFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int countByExample(SourcePageFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByExample(SourcePageFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insert(SourcePageFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insertSelective(SourcePageFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    List<SourcePageFilter> selectByExample(SourcePageFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    SourcePageFilter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExampleSelective(@Param("record") SourcePageFilter record, @Param("example") SourcePageFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExample(@Param("record") SourcePageFilter record, @Param("example") SourcePageFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKeySelective(SourcePageFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKey(SourcePageFilter record);
}