package org.cc.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cc.mybatis.model.SourcePageSample;
import org.cc.mybatis.model.SourcePageSampleExample;

public interface SourcePageSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int countByExample(SourcePageSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByExample(SourcePageSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insert(SourcePageSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int insertSelective(SourcePageSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    List<SourcePageSample> selectByExample(SourcePageSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    SourcePageSample selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExampleSelective(@Param("record") SourcePageSample record, @Param("example") SourcePageSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByExample(@Param("record") SourcePageSample record, @Param("example") SourcePageSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKeySelective(SourcePageSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page_sample
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    int updateByPrimaryKey(SourcePageSample record);
}