package org.cc.mybatis.model;

import java.util.Date;

public class Filter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String filterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.filter_class_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String filterClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.filter_class_params
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String filterClassParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.param_type
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.param_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String paramNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_filter.set_param_method_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String setParamMethodName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.id
     *
     * @return the value of tbl_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.id
     *
     * @param id the value for tbl_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.version
     *
     * @return the value of tbl_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.version
     *
     * @param version the value for tbl_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.created_by
     *
     * @return the value of tbl_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.created_by
     *
     * @param createdBy the value for tbl_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.created_dt
     *
     * @return the value of tbl_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.created_dt
     *
     * @param createdDt the value for tbl_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.updated_by
     *
     * @return the value of tbl_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.updated_by
     *
     * @param updatedBy the value for tbl_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.updated_dt
     *
     * @return the value of tbl_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.updated_dt
     *
     * @param updatedDt the value for tbl_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.filter_name
     *
     * @return the value of tbl_filter.filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getFilterName() {
        return filterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.filter_name
     *
     * @param filterName the value for tbl_filter.filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setFilterName(String filterName) {
        this.filterName = filterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.filter_class_name
     *
     * @return the value of tbl_filter.filter_class_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getFilterClassName() {
        return filterClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.filter_class_name
     *
     * @param filterClassName the value for tbl_filter.filter_class_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setFilterClassName(String filterClassName) {
        this.filterClassName = filterClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.filter_class_params
     *
     * @return the value of tbl_filter.filter_class_params
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getFilterClassParams() {
        return filterClassParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.filter_class_params
     *
     * @param filterClassParams the value for tbl_filter.filter_class_params
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setFilterClassParams(String filterClassParams) {
        this.filterClassParams = filterClassParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.param_type
     *
     * @return the value of tbl_filter.param_type
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.param_type
     *
     * @param paramType the value for tbl_filter.param_type
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.param_num
     *
     * @return the value of tbl_filter.param_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getParamNum() {
        return paramNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.param_num
     *
     * @param paramNum the value for tbl_filter.param_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setParamNum(String paramNum) {
        this.paramNum = paramNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_filter.set_param_method_name
     *
     * @return the value of tbl_filter.set_param_method_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSetParamMethodName() {
        return setParamMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_filter.set_param_method_name
     *
     * @param setParamMethodName the value for tbl_filter.set_param_method_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSetParamMethodName(String setParamMethodName) {
        this.setParamMethodName = setParamMethodName;
    }
}