package org.cc.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FilterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public FilterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNull() {
            addCriterion("created_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNotNull() {
            addCriterion("created_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtEqualTo(Date value) {
            addCriterion("created_dt =", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotEqualTo(Date value) {
            addCriterion("created_dt <>", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThan(Date value) {
            addCriterion("created_dt >", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_dt >=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThan(Date value) {
            addCriterion("created_dt <", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThanOrEqualTo(Date value) {
            addCriterion("created_dt <=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIn(List<Date> values) {
            addCriterion("created_dt in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotIn(List<Date> values) {
            addCriterion("created_dt not in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtBetween(Date value1, Date value2) {
            addCriterion("created_dt between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotBetween(Date value1, Date value2) {
            addCriterion("created_dt not between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIsNull() {
            addCriterion("updated_dt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIsNotNull() {
            addCriterion("updated_dt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtEqualTo(Date value) {
            addCriterion("updated_dt =", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotEqualTo(Date value) {
            addCriterion("updated_dt <>", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtGreaterThan(Date value) {
            addCriterion("updated_dt >", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_dt >=", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtLessThan(Date value) {
            addCriterion("updated_dt <", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtLessThanOrEqualTo(Date value) {
            addCriterion("updated_dt <=", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIn(List<Date> values) {
            addCriterion("updated_dt in", values, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotIn(List<Date> values) {
            addCriterion("updated_dt not in", values, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtBetween(Date value1, Date value2) {
            addCriterion("updated_dt between", value1, value2, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotBetween(Date value1, Date value2) {
            addCriterion("updated_dt not between", value1, value2, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andFilterNameIsNull() {
            addCriterion("filter_name is null");
            return (Criteria) this;
        }

        public Criteria andFilterNameIsNotNull() {
            addCriterion("filter_name is not null");
            return (Criteria) this;
        }

        public Criteria andFilterNameEqualTo(String value) {
            addCriterion("filter_name =", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameNotEqualTo(String value) {
            addCriterion("filter_name <>", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameGreaterThan(String value) {
            addCriterion("filter_name >", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameGreaterThanOrEqualTo(String value) {
            addCriterion("filter_name >=", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameLessThan(String value) {
            addCriterion("filter_name <", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameLessThanOrEqualTo(String value) {
            addCriterion("filter_name <=", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameLike(String value) {
            addCriterion("filter_name like", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameNotLike(String value) {
            addCriterion("filter_name not like", value, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameIn(List<String> values) {
            addCriterion("filter_name in", values, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameNotIn(List<String> values) {
            addCriterion("filter_name not in", values, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameBetween(String value1, String value2) {
            addCriterion("filter_name between", value1, value2, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterNameNotBetween(String value1, String value2) {
            addCriterion("filter_name not between", value1, value2, "filterName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameIsNull() {
            addCriterion("filter_class_name is null");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameIsNotNull() {
            addCriterion("filter_class_name is not null");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameEqualTo(String value) {
            addCriterion("filter_class_name =", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameNotEqualTo(String value) {
            addCriterion("filter_class_name <>", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameGreaterThan(String value) {
            addCriterion("filter_class_name >", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("filter_class_name >=", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameLessThan(String value) {
            addCriterion("filter_class_name <", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameLessThanOrEqualTo(String value) {
            addCriterion("filter_class_name <=", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameLike(String value) {
            addCriterion("filter_class_name like", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameNotLike(String value) {
            addCriterion("filter_class_name not like", value, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameIn(List<String> values) {
            addCriterion("filter_class_name in", values, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameNotIn(List<String> values) {
            addCriterion("filter_class_name not in", values, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameBetween(String value1, String value2) {
            addCriterion("filter_class_name between", value1, value2, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassNameNotBetween(String value1, String value2) {
            addCriterion("filter_class_name not between", value1, value2, "filterClassName");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsIsNull() {
            addCriterion("filter_class_params is null");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsIsNotNull() {
            addCriterion("filter_class_params is not null");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsEqualTo(String value) {
            addCriterion("filter_class_params =", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsNotEqualTo(String value) {
            addCriterion("filter_class_params <>", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsGreaterThan(String value) {
            addCriterion("filter_class_params >", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsGreaterThanOrEqualTo(String value) {
            addCriterion("filter_class_params >=", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsLessThan(String value) {
            addCriterion("filter_class_params <", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsLessThanOrEqualTo(String value) {
            addCriterion("filter_class_params <=", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsLike(String value) {
            addCriterion("filter_class_params like", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsNotLike(String value) {
            addCriterion("filter_class_params not like", value, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsIn(List<String> values) {
            addCriterion("filter_class_params in", values, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsNotIn(List<String> values) {
            addCriterion("filter_class_params not in", values, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsBetween(String value1, String value2) {
            addCriterion("filter_class_params between", value1, value2, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andFilterClassParamsNotBetween(String value1, String value2) {
            addCriterion("filter_class_params not between", value1, value2, "filterClassParams");
            return (Criteria) this;
        }

        public Criteria andParamTypeIsNull() {
            addCriterion("param_type is null");
            return (Criteria) this;
        }

        public Criteria andParamTypeIsNotNull() {
            addCriterion("param_type is not null");
            return (Criteria) this;
        }

        public Criteria andParamTypeEqualTo(String value) {
            addCriterion("param_type =", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotEqualTo(String value) {
            addCriterion("param_type <>", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeGreaterThan(String value) {
            addCriterion("param_type >", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeGreaterThanOrEqualTo(String value) {
            addCriterion("param_type >=", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLessThan(String value) {
            addCriterion("param_type <", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLessThanOrEqualTo(String value) {
            addCriterion("param_type <=", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLike(String value) {
            addCriterion("param_type like", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotLike(String value) {
            addCriterion("param_type not like", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeIn(List<String> values) {
            addCriterion("param_type in", values, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotIn(List<String> values) {
            addCriterion("param_type not in", values, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeBetween(String value1, String value2) {
            addCriterion("param_type between", value1, value2, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotBetween(String value1, String value2) {
            addCriterion("param_type not between", value1, value2, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamNumIsNull() {
            addCriterion("param_num is null");
            return (Criteria) this;
        }

        public Criteria andParamNumIsNotNull() {
            addCriterion("param_num is not null");
            return (Criteria) this;
        }

        public Criteria andParamNumEqualTo(String value) {
            addCriterion("param_num =", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumNotEqualTo(String value) {
            addCriterion("param_num <>", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumGreaterThan(String value) {
            addCriterion("param_num >", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumGreaterThanOrEqualTo(String value) {
            addCriterion("param_num >=", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumLessThan(String value) {
            addCriterion("param_num <", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumLessThanOrEqualTo(String value) {
            addCriterion("param_num <=", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumLike(String value) {
            addCriterion("param_num like", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumNotLike(String value) {
            addCriterion("param_num not like", value, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumIn(List<String> values) {
            addCriterion("param_num in", values, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumNotIn(List<String> values) {
            addCriterion("param_num not in", values, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumBetween(String value1, String value2) {
            addCriterion("param_num between", value1, value2, "paramNum");
            return (Criteria) this;
        }

        public Criteria andParamNumNotBetween(String value1, String value2) {
            addCriterion("param_num not between", value1, value2, "paramNum");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameIsNull() {
            addCriterion("set_param_method_name is null");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameIsNotNull() {
            addCriterion("set_param_method_name is not null");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameEqualTo(String value) {
            addCriterion("set_param_method_name =", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameNotEqualTo(String value) {
            addCriterion("set_param_method_name <>", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameGreaterThan(String value) {
            addCriterion("set_param_method_name >", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("set_param_method_name >=", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameLessThan(String value) {
            addCriterion("set_param_method_name <", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameLessThanOrEqualTo(String value) {
            addCriterion("set_param_method_name <=", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameLike(String value) {
            addCriterion("set_param_method_name like", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameNotLike(String value) {
            addCriterion("set_param_method_name not like", value, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameIn(List<String> values) {
            addCriterion("set_param_method_name in", values, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameNotIn(List<String> values) {
            addCriterion("set_param_method_name not in", values, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameBetween(String value1, String value2) {
            addCriterion("set_param_method_name between", value1, value2, "setParamMethodName");
            return (Criteria) this;
        }

        public Criteria andSetParamMethodNameNotBetween(String value1, String value2) {
            addCriterion("set_param_method_name not between", value1, value2, "setParamMethodName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_filter
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 08 16:12:34 SGT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_filter
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}