package org.cc.mybatis.model;

import java.util.Date;

public class SourcePageCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_category.name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.id
     *
     * @return the value of tbl_source_page_category.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.id
     *
     * @param id the value for tbl_source_page_category.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.version
     *
     * @return the value of tbl_source_page_category.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.version
     *
     * @param version the value for tbl_source_page_category.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.created_by
     *
     * @return the value of tbl_source_page_category.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.created_by
     *
     * @param createdBy the value for tbl_source_page_category.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.created_dt
     *
     * @return the value of tbl_source_page_category.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.created_dt
     *
     * @param createdDt the value for tbl_source_page_category.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.updated_by
     *
     * @return the value of tbl_source_page_category.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.updated_by
     *
     * @param updatedBy the value for tbl_source_page_category.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.updated_dt
     *
     * @return the value of tbl_source_page_category.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.updated_dt
     *
     * @param updatedDt the value for tbl_source_page_category.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_category.name
     *
     * @return the value of tbl_source_page_category.name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_category.name
     *
     * @param name the value for tbl_source_page_category.name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}