package org.cc.mybatis.model;

import java.util.Date;

public class SourcePageFilter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String spSampleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.source_page_filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String sourcePageFilterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter.seq_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer seqNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.id
     *
     * @return the value of tbl_source_page_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.id
     *
     * @param id the value for tbl_source_page_filter.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.version
     *
     * @return the value of tbl_source_page_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.version
     *
     * @param version the value for tbl_source_page_filter.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.created_by
     *
     * @return the value of tbl_source_page_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.created_by
     *
     * @param createdBy the value for tbl_source_page_filter.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.created_dt
     *
     * @return the value of tbl_source_page_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.created_dt
     *
     * @param createdDt the value for tbl_source_page_filter.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.updated_by
     *
     * @return the value of tbl_source_page_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.updated_by
     *
     * @param updatedBy the value for tbl_source_page_filter.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.updated_dt
     *
     * @return the value of tbl_source_page_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.updated_dt
     *
     * @param updatedDt the value for tbl_source_page_filter.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.sp_sample_id
     *
     * @return the value of tbl_source_page_filter.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSpSampleId() {
        return spSampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.sp_sample_id
     *
     * @param spSampleId the value for tbl_source_page_filter.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSpSampleId(String spSampleId) {
        this.spSampleId = spSampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.source_page_filter_name
     *
     * @return the value of tbl_source_page_filter.source_page_filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSourcePageFilterName() {
        return sourcePageFilterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.source_page_filter_name
     *
     * @param sourcePageFilterName the value for tbl_source_page_filter.source_page_filter_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSourcePageFilterName(String sourcePageFilterName) {
        this.sourcePageFilterName = sourcePageFilterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter.seq_num
     *
     * @return the value of tbl_source_page_filter.seq_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getSeqNum() {
        return seqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter.seq_num
     *
     * @param seqNum the value for tbl_source_page_filter.seq_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSeqNum(Integer seqNum) {
        this.seqNum = seqNum;
    }
}