package org.cc.mybatis.model;

import java.util.Date;

public class SourcePage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.target_page_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String targetPageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.target_page_url
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String targetPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.status
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.md5_code
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String md5Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.sample_sp_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String sampleSpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.unique_label
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String uniqueLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.sub_sp_domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String subSpDomainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.sample_sp_id_for_navi_sp
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String sampleSpIdForNaviSp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String spSampleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.id
     *
     * @return the value of tbl_source_page.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.id
     *
     * @param id the value for tbl_source_page.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.version
     *
     * @return the value of tbl_source_page.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.version
     *
     * @param version the value for tbl_source_page.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.created_by
     *
     * @return the value of tbl_source_page.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.created_by
     *
     * @param createdBy the value for tbl_source_page.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.created_dt
     *
     * @return the value of tbl_source_page.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.created_dt
     *
     * @param createdDt the value for tbl_source_page.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.updated_by
     *
     * @return the value of tbl_source_page.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.updated_by
     *
     * @param updatedBy the value for tbl_source_page.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.updated_dt
     *
     * @return the value of tbl_source_page.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.updated_dt
     *
     * @param updatedDt the value for tbl_source_page.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.target_page_name
     *
     * @return the value of tbl_source_page.target_page_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getTargetPageName() {
        return targetPageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.target_page_name
     *
     * @param targetPageName the value for tbl_source_page.target_page_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setTargetPageName(String targetPageName) {
        this.targetPageName = targetPageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.target_page_url
     *
     * @return the value of tbl_source_page.target_page_url
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getTargetPageUrl() {
        return targetPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.target_page_url
     *
     * @param targetPageUrl the value for tbl_source_page.target_page_url
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setTargetPageUrl(String targetPageUrl) {
        this.targetPageUrl = targetPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.category
     *
     * @return the value of tbl_source_page.category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.category
     *
     * @param category the value for tbl_source_page.category
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.status
     *
     * @return the value of tbl_source_page.status
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.status
     *
     * @param status the value for tbl_source_page.status
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.domain_name
     *
     * @return the value of tbl_source_page.domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.domain_name
     *
     * @param domainName the value for tbl_source_page.domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.md5_code
     *
     * @return the value of tbl_source_page.md5_code
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getMd5Code() {
        return md5Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.md5_code
     *
     * @param md5Code the value for tbl_source_page.md5_code
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setMd5Code(String md5Code) {
        this.md5Code = md5Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.sample_sp_id
     *
     * @return the value of tbl_source_page.sample_sp_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSampleSpId() {
        return sampleSpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.sample_sp_id
     *
     * @param sampleSpId the value for tbl_source_page.sample_sp_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSampleSpId(String sampleSpId) {
        this.sampleSpId = sampleSpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.unique_label
     *
     * @return the value of tbl_source_page.unique_label
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUniqueLabel() {
        return uniqueLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.unique_label
     *
     * @param uniqueLabel the value for tbl_source_page.unique_label
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUniqueLabel(String uniqueLabel) {
        this.uniqueLabel = uniqueLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.sub_sp_domain_name
     *
     * @return the value of tbl_source_page.sub_sp_domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSubSpDomainName() {
        return subSpDomainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.sub_sp_domain_name
     *
     * @param subSpDomainName the value for tbl_source_page.sub_sp_domain_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSubSpDomainName(String subSpDomainName) {
        this.subSpDomainName = subSpDomainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.sample_sp_id_for_navi_sp
     *
     * @return the value of tbl_source_page.sample_sp_id_for_navi_sp
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSampleSpIdForNaviSp() {
        return sampleSpIdForNaviSp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.sample_sp_id_for_navi_sp
     *
     * @param sampleSpIdForNaviSp the value for tbl_source_page.sample_sp_id_for_navi_sp
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSampleSpIdForNaviSp(String sampleSpIdForNaviSp) {
        this.sampleSpIdForNaviSp = sampleSpIdForNaviSp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page.sp_sample_id
     *
     * @return the value of tbl_source_page.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSpSampleId() {
        return spSampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page.sp_sample_id
     *
     * @param spSampleId the value for tbl_source_page.sp_sample_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSpSampleId(String spSampleId) {
        this.spSampleId = spSampleId;
    }
}