package org.cc.mybatis.model;

import java.util.Date;

public class SourcePageFilterDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.page_filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String pageFilterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String filterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.param_value1
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String paramValue1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.param_value2
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String paramValue2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.parent_node_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String parentNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_filter_detail.sub_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer subNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.id
     *
     * @return the value of tbl_source_page_filter_detail.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.id
     *
     * @param id the value for tbl_source_page_filter_detail.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.version
     *
     * @return the value of tbl_source_page_filter_detail.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.version
     *
     * @param version the value for tbl_source_page_filter_detail.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.created_by
     *
     * @return the value of tbl_source_page_filter_detail.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.created_by
     *
     * @param createdBy the value for tbl_source_page_filter_detail.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.created_dt
     *
     * @return the value of tbl_source_page_filter_detail.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.created_dt
     *
     * @param createdDt the value for tbl_source_page_filter_detail.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.updated_by
     *
     * @return the value of tbl_source_page_filter_detail.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.updated_by
     *
     * @param updatedBy the value for tbl_source_page_filter_detail.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.updated_dt
     *
     * @return the value of tbl_source_page_filter_detail.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.updated_dt
     *
     * @param updatedDt the value for tbl_source_page_filter_detail.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.page_filter_id
     *
     * @return the value of tbl_source_page_filter_detail.page_filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getPageFilterId() {
        return pageFilterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.page_filter_id
     *
     * @param pageFilterId the value for tbl_source_page_filter_detail.page_filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setPageFilterId(String pageFilterId) {
        this.pageFilterId = pageFilterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.filter_id
     *
     * @return the value of tbl_source_page_filter_detail.filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getFilterId() {
        return filterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.filter_id
     *
     * @param filterId the value for tbl_source_page_filter_detail.filter_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setFilterId(String filterId) {
        this.filterId = filterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.param_value1
     *
     * @return the value of tbl_source_page_filter_detail.param_value1
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getParamValue1() {
        return paramValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.param_value1
     *
     * @param paramValue1 the value for tbl_source_page_filter_detail.param_value1
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setParamValue1(String paramValue1) {
        this.paramValue1 = paramValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.param_value2
     *
     * @return the value of tbl_source_page_filter_detail.param_value2
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getParamValue2() {
        return paramValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.param_value2
     *
     * @param paramValue2 the value for tbl_source_page_filter_detail.param_value2
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setParamValue2(String paramValue2) {
        this.paramValue2 = paramValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.parent_node_id
     *
     * @return the value of tbl_source_page_filter_detail.parent_node_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getParentNodeId() {
        return parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.parent_node_id
     *
     * @param parentNodeId the value for tbl_source_page_filter_detail.parent_node_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setParentNodeId(String parentNodeId) {
        this.parentNodeId = parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_filter_detail.sub_num
     *
     * @return the value of tbl_source_page_filter_detail.sub_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_filter_detail.sub_num
     *
     * @param subNum the value for tbl_source_page_filter_detail.sub_num
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSubNum(Integer subNum) {
        this.subNum = subNum;
    }
}