package org.cc.mybatis.model;

import java.util.Date;

public class SourcePageSample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.sample_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String sampleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.logo
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_source_page_sample.sp_category_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    private String spCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.id
     *
     * @return the value of tbl_source_page_sample.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.id
     *
     * @param id the value for tbl_source_page_sample.id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.version
     *
     * @return the value of tbl_source_page_sample.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.version
     *
     * @param version the value for tbl_source_page_sample.version
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.created_by
     *
     * @return the value of tbl_source_page_sample.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.created_by
     *
     * @param createdBy the value for tbl_source_page_sample.created_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.created_dt
     *
     * @return the value of tbl_source_page_sample.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.created_dt
     *
     * @param createdDt the value for tbl_source_page_sample.created_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.updated_by
     *
     * @return the value of tbl_source_page_sample.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.updated_by
     *
     * @param updatedBy the value for tbl_source_page_sample.updated_by
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.updated_dt
     *
     * @return the value of tbl_source_page_sample.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.updated_dt
     *
     * @param updatedDt the value for tbl_source_page_sample.updated_dt
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.sample_name
     *
     * @return the value of tbl_source_page_sample.sample_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.sample_name
     *
     * @param sampleName the value for tbl_source_page_sample.sample_name
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.logo
     *
     * @return the value of tbl_source_page_sample.logo
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.logo
     *
     * @param logo the value for tbl_source_page_sample.logo
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_source_page_sample.sp_category_id
     *
     * @return the value of tbl_source_page_sample.sp_category_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getSpCategoryId() {
        return spCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_source_page_sample.sp_category_id
     *
     * @param spCategoryId the value for tbl_source_page_sample.sp_category_id
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setSpCategoryId(String spCategoryId) {
        this.spCategoryId = spCategoryId;
    }
}