package org.cc.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SourcePageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public SourcePageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNull() {
            addCriterion("created_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNotNull() {
            addCriterion("created_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtEqualTo(Date value) {
            addCriterion("created_dt =", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotEqualTo(Date value) {
            addCriterion("created_dt <>", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThan(Date value) {
            addCriterion("created_dt >", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_dt >=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThan(Date value) {
            addCriterion("created_dt <", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThanOrEqualTo(Date value) {
            addCriterion("created_dt <=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIn(List<Date> values) {
            addCriterion("created_dt in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotIn(List<Date> values) {
            addCriterion("created_dt not in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtBetween(Date value1, Date value2) {
            addCriterion("created_dt between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotBetween(Date value1, Date value2) {
            addCriterion("created_dt not between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIsNull() {
            addCriterion("updated_dt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIsNotNull() {
            addCriterion("updated_dt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtEqualTo(Date value) {
            addCriterion("updated_dt =", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotEqualTo(Date value) {
            addCriterion("updated_dt <>", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtGreaterThan(Date value) {
            addCriterion("updated_dt >", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_dt >=", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtLessThan(Date value) {
            addCriterion("updated_dt <", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtLessThanOrEqualTo(Date value) {
            addCriterion("updated_dt <=", value, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtIn(List<Date> values) {
            addCriterion("updated_dt in", values, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotIn(List<Date> values) {
            addCriterion("updated_dt not in", values, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtBetween(Date value1, Date value2) {
            addCriterion("updated_dt between", value1, value2, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andUpdatedDtNotBetween(Date value1, Date value2) {
            addCriterion("updated_dt not between", value1, value2, "updatedDt");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameIsNull() {
            addCriterion("target_page_name is null");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameIsNotNull() {
            addCriterion("target_page_name is not null");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameEqualTo(String value) {
            addCriterion("target_page_name =", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameNotEqualTo(String value) {
            addCriterion("target_page_name <>", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameGreaterThan(String value) {
            addCriterion("target_page_name >", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameGreaterThanOrEqualTo(String value) {
            addCriterion("target_page_name >=", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameLessThan(String value) {
            addCriterion("target_page_name <", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameLessThanOrEqualTo(String value) {
            addCriterion("target_page_name <=", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameLike(String value) {
            addCriterion("target_page_name like", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameNotLike(String value) {
            addCriterion("target_page_name not like", value, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameIn(List<String> values) {
            addCriterion("target_page_name in", values, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameNotIn(List<String> values) {
            addCriterion("target_page_name not in", values, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameBetween(String value1, String value2) {
            addCriterion("target_page_name between", value1, value2, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageNameNotBetween(String value1, String value2) {
            addCriterion("target_page_name not between", value1, value2, "targetPageName");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlIsNull() {
            addCriterion("target_page_url is null");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlIsNotNull() {
            addCriterion("target_page_url is not null");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlEqualTo(String value) {
            addCriterion("target_page_url =", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlNotEqualTo(String value) {
            addCriterion("target_page_url <>", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlGreaterThan(String value) {
            addCriterion("target_page_url >", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("target_page_url >=", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlLessThan(String value) {
            addCriterion("target_page_url <", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlLessThanOrEqualTo(String value) {
            addCriterion("target_page_url <=", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlLike(String value) {
            addCriterion("target_page_url like", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlNotLike(String value) {
            addCriterion("target_page_url not like", value, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlIn(List<String> values) {
            addCriterion("target_page_url in", values, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlNotIn(List<String> values) {
            addCriterion("target_page_url not in", values, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlBetween(String value1, String value2) {
            addCriterion("target_page_url between", value1, value2, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetPageUrlNotBetween(String value1, String value2) {
            addCriterion("target_page_url not between", value1, value2, "targetPageUrl");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDomainNameIsNull() {
            addCriterion("domain_name is null");
            return (Criteria) this;
        }

        public Criteria andDomainNameIsNotNull() {
            addCriterion("domain_name is not null");
            return (Criteria) this;
        }

        public Criteria andDomainNameEqualTo(String value) {
            addCriterion("domain_name =", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotEqualTo(String value) {
            addCriterion("domain_name <>", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameGreaterThan(String value) {
            addCriterion("domain_name >", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameGreaterThanOrEqualTo(String value) {
            addCriterion("domain_name >=", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLessThan(String value) {
            addCriterion("domain_name <", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLessThanOrEqualTo(String value) {
            addCriterion("domain_name <=", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLike(String value) {
            addCriterion("domain_name like", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotLike(String value) {
            addCriterion("domain_name not like", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameIn(List<String> values) {
            addCriterion("domain_name in", values, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotIn(List<String> values) {
            addCriterion("domain_name not in", values, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameBetween(String value1, String value2) {
            addCriterion("domain_name between", value1, value2, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotBetween(String value1, String value2) {
            addCriterion("domain_name not between", value1, value2, "domainName");
            return (Criteria) this;
        }

        public Criteria andMd5CodeIsNull() {
            addCriterion("md5_code is null");
            return (Criteria) this;
        }

        public Criteria andMd5CodeIsNotNull() {
            addCriterion("md5_code is not null");
            return (Criteria) this;
        }

        public Criteria andMd5CodeEqualTo(String value) {
            addCriterion("md5_code =", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeNotEqualTo(String value) {
            addCriterion("md5_code <>", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeGreaterThan(String value) {
            addCriterion("md5_code >", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeGreaterThanOrEqualTo(String value) {
            addCriterion("md5_code >=", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeLessThan(String value) {
            addCriterion("md5_code <", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeLessThanOrEqualTo(String value) {
            addCriterion("md5_code <=", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeLike(String value) {
            addCriterion("md5_code like", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeNotLike(String value) {
            addCriterion("md5_code not like", value, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeIn(List<String> values) {
            addCriterion("md5_code in", values, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeNotIn(List<String> values) {
            addCriterion("md5_code not in", values, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeBetween(String value1, String value2) {
            addCriterion("md5_code between", value1, value2, "md5Code");
            return (Criteria) this;
        }

        public Criteria andMd5CodeNotBetween(String value1, String value2) {
            addCriterion("md5_code not between", value1, value2, "md5Code");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdIsNull() {
            addCriterion("sample_sp_id is null");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdIsNotNull() {
            addCriterion("sample_sp_id is not null");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdEqualTo(String value) {
            addCriterion("sample_sp_id =", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdNotEqualTo(String value) {
            addCriterion("sample_sp_id <>", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdGreaterThan(String value) {
            addCriterion("sample_sp_id >", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("sample_sp_id >=", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdLessThan(String value) {
            addCriterion("sample_sp_id <", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdLessThanOrEqualTo(String value) {
            addCriterion("sample_sp_id <=", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdLike(String value) {
            addCriterion("sample_sp_id like", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdNotLike(String value) {
            addCriterion("sample_sp_id not like", value, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdIn(List<String> values) {
            addCriterion("sample_sp_id in", values, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdNotIn(List<String> values) {
            addCriterion("sample_sp_id not in", values, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdBetween(String value1, String value2) {
            addCriterion("sample_sp_id between", value1, value2, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdNotBetween(String value1, String value2) {
            addCriterion("sample_sp_id not between", value1, value2, "sampleSpId");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelIsNull() {
            addCriterion("unique_label is null");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelIsNotNull() {
            addCriterion("unique_label is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelEqualTo(String value) {
            addCriterion("unique_label =", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelNotEqualTo(String value) {
            addCriterion("unique_label <>", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelGreaterThan(String value) {
            addCriterion("unique_label >", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelGreaterThanOrEqualTo(String value) {
            addCriterion("unique_label >=", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelLessThan(String value) {
            addCriterion("unique_label <", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelLessThanOrEqualTo(String value) {
            addCriterion("unique_label <=", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelLike(String value) {
            addCriterion("unique_label like", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelNotLike(String value) {
            addCriterion("unique_label not like", value, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelIn(List<String> values) {
            addCriterion("unique_label in", values, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelNotIn(List<String> values) {
            addCriterion("unique_label not in", values, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelBetween(String value1, String value2) {
            addCriterion("unique_label between", value1, value2, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andUniqueLabelNotBetween(String value1, String value2) {
            addCriterion("unique_label not between", value1, value2, "uniqueLabel");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameIsNull() {
            addCriterion("sub_sp_domain_name is null");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameIsNotNull() {
            addCriterion("sub_sp_domain_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameEqualTo(String value) {
            addCriterion("sub_sp_domain_name =", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameNotEqualTo(String value) {
            addCriterion("sub_sp_domain_name <>", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameGreaterThan(String value) {
            addCriterion("sub_sp_domain_name >", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameGreaterThanOrEqualTo(String value) {
            addCriterion("sub_sp_domain_name >=", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameLessThan(String value) {
            addCriterion("sub_sp_domain_name <", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameLessThanOrEqualTo(String value) {
            addCriterion("sub_sp_domain_name <=", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameLike(String value) {
            addCriterion("sub_sp_domain_name like", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameNotLike(String value) {
            addCriterion("sub_sp_domain_name not like", value, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameIn(List<String> values) {
            addCriterion("sub_sp_domain_name in", values, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameNotIn(List<String> values) {
            addCriterion("sub_sp_domain_name not in", values, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameBetween(String value1, String value2) {
            addCriterion("sub_sp_domain_name between", value1, value2, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSubSpDomainNameNotBetween(String value1, String value2) {
            addCriterion("sub_sp_domain_name not between", value1, value2, "subSpDomainName");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpIsNull() {
            addCriterion("sample_sp_id_for_navi_sp is null");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpIsNotNull() {
            addCriterion("sample_sp_id_for_navi_sp is not null");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpEqualTo(String value) {
            addCriterion("sample_sp_id_for_navi_sp =", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpNotEqualTo(String value) {
            addCriterion("sample_sp_id_for_navi_sp <>", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpGreaterThan(String value) {
            addCriterion("sample_sp_id_for_navi_sp >", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpGreaterThanOrEqualTo(String value) {
            addCriterion("sample_sp_id_for_navi_sp >=", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpLessThan(String value) {
            addCriterion("sample_sp_id_for_navi_sp <", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpLessThanOrEqualTo(String value) {
            addCriterion("sample_sp_id_for_navi_sp <=", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpLike(String value) {
            addCriterion("sample_sp_id_for_navi_sp like", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpNotLike(String value) {
            addCriterion("sample_sp_id_for_navi_sp not like", value, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpIn(List<String> values) {
            addCriterion("sample_sp_id_for_navi_sp in", values, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpNotIn(List<String> values) {
            addCriterion("sample_sp_id_for_navi_sp not in", values, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpBetween(String value1, String value2) {
            addCriterion("sample_sp_id_for_navi_sp between", value1, value2, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSampleSpIdForNaviSpNotBetween(String value1, String value2) {
            addCriterion("sample_sp_id_for_navi_sp not between", value1, value2, "sampleSpIdForNaviSp");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdIsNull() {
            addCriterion("sp_sample_id is null");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdIsNotNull() {
            addCriterion("sp_sample_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdEqualTo(String value) {
            addCriterion("sp_sample_id =", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdNotEqualTo(String value) {
            addCriterion("sp_sample_id <>", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdGreaterThan(String value) {
            addCriterion("sp_sample_id >", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdGreaterThanOrEqualTo(String value) {
            addCriterion("sp_sample_id >=", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdLessThan(String value) {
            addCriterion("sp_sample_id <", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdLessThanOrEqualTo(String value) {
            addCriterion("sp_sample_id <=", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdLike(String value) {
            addCriterion("sp_sample_id like", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdNotLike(String value) {
            addCriterion("sp_sample_id not like", value, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdIn(List<String> values) {
            addCriterion("sp_sample_id in", values, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdNotIn(List<String> values) {
            addCriterion("sp_sample_id not in", values, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdBetween(String value1, String value2) {
            addCriterion("sp_sample_id between", value1, value2, "spSampleId");
            return (Criteria) this;
        }

        public Criteria andSpSampleIdNotBetween(String value1, String value2) {
            addCriterion("sp_sample_id not between", value1, value2, "spSampleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_source_page
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 08 16:12:34 SGT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_source_page
     *
     * @mbggenerated Wed Oct 08 16:12:34 SGT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}